# Generated by Django 3.2.15 on 2022-09-19 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('url', models.URLField()),
                ('author', models.CharField(max_length=200)),
                ('hacker_news_id', models.BigIntegerField(primary_key=True, serialize=False, unique=True)),
                ('date_created', models.DateTimeField()),
            ],
        ),
    ]
