# Generated by Django 3.2.15 on 2022-09-20 15:00

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('author', models.CharField(max_length=200)),
                ('title', models.CharField(default='none', max_length=200)),
                ('type', models.CharField(default='none', max_length=200)),
                ('hacker_news_id', models.BigIntegerField(unique=True)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=200)),
                ('text', models.TextField(default='Text')),
                ('type', models.CharField(default='none', max_length=200)),
                ('hacker_comment_id', models.BigIntegerField(unique=True)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.news')),
            ],
        ),
    ]
