# Generated by Django 3.2.15 on 2022-09-21 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_news_origin'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='body',
            field=models.TextField(default='none'),
        ),
        migrations.AlterField(
            model_name='news',
            name='author',
            field=models.CharField(default='mainuser', max_length=200),
        ),
        migrations.AlterField(
            model_name='news',
            name='hacker_news_id',
            field=models.BigIntegerField(default=0, unique=True),
        ),
    ]
