# Generated by Django 3.2.15 on 2022-09-19 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20220919_1133'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='date_created',
        ),
    ]
