# Generated by Django 3.2.15 on 2022-09-19 12:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_remove_news_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 19, 12, 11, 49, 656850)),
        ),
    ]
