# Generated by Django 3.2.15 on 2022-09-19 12:38

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_news_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 19, 12, 38, 2, 702273)),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('author', models.CharField(max_length=200)),
                ('title', models.CharField(default='none', max_length=200)),
                ('type', models.CharField(default='none', max_length=200)),
                ('hacker_news_id', models.BigIntegerField(primary_key=True, serialize=False, unique=True)),
                ('date_created', models.DateTimeField(default=datetime.datetime(2022, 9, 19, 12, 38, 2, 702937))),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.news')),
            ],
        ),
    ]
