# Generated by Django 3.2.15 on 2022-09-19 13:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_auto_20220919_1238'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='question',
            new_name='news',
        ),
        migrations.AddField(
            model_name='comment',
            name='text',
            field=models.TextField(default='Text'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 19, 13, 9, 49, 371795)),
        ),
        migrations.AlterField(
            model_name='news',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 19, 13, 9, 49, 371111)),
        ),
    ]
