# Generated by Django 3.2.15 on 2022-09-19 13:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_auto_20220919_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 19, 13, 27, 30, 353468)),
        ),
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.CharField(default='Text', max_length=500),
        ),
        migrations.AlterField(
            model_name='news',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 19, 13, 27, 30, 352784)),
        ),
    ]
