# Generated by Django 3.2.15 on 2022-09-19 14:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_auto_20220919_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 19, 14, 14, 52, 670553)),
        ),
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.TextField(default='Text'),
        ),
        migrations.AlterField(
            model_name='news',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 19, 14, 14, 52, 669838)),
        ),
    ]
